// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuth() {
  return window['go']['main']['App']['CheckAuth']();
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DoRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DoRequest'](arg1, arg2, arg3, arg4);
}

export function GetFile(arg1, arg2) {
  return window['go']['main']['App']['GetFile'](arg1, arg2);
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function NewFile(arg1) {
  return window['go']['main']['App']['NewFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SearchFiles(arg1) {
  return window['go']['main']['App']['SearchFiles'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function UpdateMetadata(arg1, arg2) {
  return window['go']['main']['App']['UpdateMetadata'](arg1, arg2);
}

export function UploadImage(arg1, arg2) {
  return window['go']['main']['App']['UploadImage'](arg1, arg2);
}

export function UploadImageBlob(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadImageBlob'](arg1, arg2, arg3);
}

export function VerifyPassword(arg1, arg2) {
  return window['go']['main']['App']['VerifyPassword'](arg1, arg2);
}
