// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuth():Promise<string>;

export function DeleteFile(arg1:string):Promise<string>;

export function DoRequest(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<string>;

export function GetFile(arg1:string,arg2:string):Promise<string>;

export function GetFiles():Promise<string>;

export function GetServerURL():Promise<string>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Logout():Promise<string>;

export function NewFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SearchFiles(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;

export function SetServerURL(arg1:string):Promise<void>;

export function UpdateMetadata(arg1:string,arg2:string):Promise<string>;

export function UploadImage(arg1:string,arg2:string):Promise<string>;

export function UploadImageBlob(arg1:string,arg2:string,arg3:string):Promise<string>;

export function VerifyPassword(arg1:string,arg2:string):Promise<string>;
